// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace autisamdata.Models
{
    public partial class Aboutus
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Contex { get; set; }
        public string Point { get; set; }
    }
}