// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace autisamdata.Models
{
    public partial class Founder
    {
        public int Id { get; set; }
        public string FounderPhoto { get; set; }
        public string FounderName { get; set; }
        public string FounderContext { get; set; }
    }
}