// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace autisamdata.Models
{
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Discription { get; set; }
        public string Text { get; set; }
        public string Essay { get; set; }
    }
}